// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh6vTGXboZ_doWrq7TAHmzssUyHxg354Q',
    appId: '1:870557967336:web:1b326258f09b40ee3e3a5d',
    messagingSenderId: '870557967336',
    projectId: 'gen-lang-client-0058397945',
    authDomain: 'gen-lang-client-0058397945.firebaseapp.com',
    storageBucket: 'gen-lang-client-0058397945.firebasestorage.app',
    measurementId: 'G-6ELBTL4FEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsF289Aw6Spf_qv6-OZZ-tATgUMPYBaQ8',
    appId: '1:870557967336:android:84a9069138042c843e3a5d',
    messagingSenderId: '870557967336',
    projectId: 'gen-lang-client-0058397945',
    storageBucket: 'gen-lang-client-0058397945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_U3oll4gqsd7GfPEaA3_625KVQZfDjM',
    appId: '1:870557967336:ios:fcf5a5213c30c35c3e3a5d',
    messagingSenderId: '870557967336',
    projectId: 'gen-lang-client-0058397945',
    storageBucket: 'gen-lang-client-0058397945.firebasestorage.app',
    iosBundleId: 'xyz.iqded.iqded',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP_U3oll4gqsd7GfPEaA3_625KVQZfDjM',
    appId: '1:870557967336:ios:fcf5a5213c30c35c3e3a5d',
    messagingSenderId: '870557967336',
    projectId: 'gen-lang-client-0058397945',
    storageBucket: 'gen-lang-client-0058397945.firebasestorage.app',
    iosBundleId: 'xyz.iqded.iqded',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAh6vTGXboZ_doWrq7TAHmzssUyHxg354Q',
    appId: '1:870557967336:web:b2be10a7093f3e403e3a5d',
    messagingSenderId: '870557967336',
    projectId: 'gen-lang-client-0058397945',
    authDomain: 'gen-lang-client-0058397945.firebaseapp.com',
    storageBucket: 'gen-lang-client-0058397945.firebasestorage.app',
    measurementId: 'G-6ZTCM9KTEC',
  );
}
