// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:iqded/features/quizPage/data/models/question_model.dart';
import 'package:iqded/features/quizPage/data/models/questions_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionsModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(QuestionModelAdapter());
    registerAdapter(QuestionsModelAdapter());
  }
}
